# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'


pod 'AFNetworking', '~> 3.1.0'

pod 'SDWebImage', '~> 3.8.2'

pod 'MJRefresh', '~> 3.1.12'

pod 'Masonry', '~> 1.0.2'

pod 'MMDrawerController', '~> 0.6.0'

pod 'YYModel', '~> 1.0.4'

pod 'JT3DScrollView', '~> 1.0.4'

pod 'DKNightVersion', '~> 2.4.0'

target 'SQ_ SateCouncilNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SQ_ SateCouncilNews

  target 'SQ_ SateCouncilNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SQ_ SateCouncilNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
